# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    az bicep build --file $(Build.SourcesDirectory)/vm28.bicep
  displayName: 'Validate the syntax using Azure Bicep CLI'

