# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  path: tempfile

- script: |
    cd tempfile
    echo Validating the syntax...
    az bicep build --template-file vm28.bicep 
  displayName: 'Validate syntax'

- script: |
    echo Deploying resources to Azure...
    az deployment group create --template-file vm28.bicep 
  displayName: 'Deploy to Azure'