# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- script: |
    az login
    az deployment group validate --resourse-group ARM1 --template-file vm12.json
  displayName: 'Validate the syntax using CLI'

- script: |
    echo Deploying resources to Azure
    az deployment group create --resource-group ARM1 --template-file vm12.json
  displayName: 'Deploy the resources to Azure'