name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate syntax
      run: |
        az  bicep build --file vm.bicep

    - name: Deploy to Azure
      run: |   
         az login
         az deployment group create --resource-group bicep3 --template-file vm.bicep
